version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY='vr8prv^o0o*ih*mtx&3uq156%4qy!u8%pbffbbfy04(#_(sl7u'
      - ALLOWED_HOSTS=127.0.0.1,localhost,webdemosite.azurewebsites.net

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data:
