# Generated by Django 3.1.3 on 2020-11-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='feeds',
        ),
    ]
