# Generated by Django 3.1.3 on 2020-11-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201113_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='overview',
            field=models.TextField(max_length=20),
        ),
    ]
