# Generated by Django 3.1.3 on 2020-11-14 05:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201114_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='description',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
    ]
