# Generated by Django 3.1.3 on 2020-11-14 10:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=tinymce.models.HTMLField(default='test'),
            preserve_default=False,
        ),
    ]
