# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-24 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import open_news.models


class Migration(migrations.Migration):

    dependencies = [
        ('open_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=open_news.models.upload_location)),
            ],
        ),
    ]
